del  .\PZIOT.Api\bin\*.*   /s /q
del  .\PZIOT.Api\obj\*.*   /s /q
del  .\PZIOT.Api\wwwroot\ui\*.*   /s /q
del  .\PZIOT.Api\WMBlog.db   /s /q
del  .\PZIOT.Common\bin\*.*   /s /q
del  .\PZIOT.Common\obj\*.*   /s /q
del  .\PZIOT.EventBus\bin\*.*   /s /q
del  .\PZIOT.EventBus\obj\*.*   /s /q
del  .\PZIOT.Extensions\bin\*.*   /s /q
del  .\PZIOT.FrameWork\bin\*.*   /s /q
del  .\PZIOT.Gateway\bin\*.*   /s /q
del  .\PZIOT.IServices\bin\*.*   /s /q
del  .\PZIOT.Model\bin\*.*   /s /q
del  .\PZIOT.Repository\bin\*.*   /s /q
del  .\PZIOT.Serilog.Es\bin\*.*   /s /q
del  .\PZIOT.Services\bin\*.*   /s /q
del  .\PZIOT.Tasks\bin\*.*   /s /q
del  .\PZIOT.Tests\bin\*.*   /s /q
del  .\Ocelot.Provider.Nacos\bin\*.*   /s /q

del  .\PZIOT.Extensions\obj\*.*   /s /q
del  .\PZIOT.FrameWork\obj\*.*   /s /q
del  .\PZIOT.Gateway\obj\*.*   /s /q
del  .\PZIOT.IServices\obj\*.*   /s /q
del  .\PZIOT.Model\obj\*.*   /s /q
del  .\PZIOT.Repository\obj\*.*   /s /q
del  .\PZIOT.Serilog.Es\obj\*.*   /s /q
del  .\PZIOT.Services\obj\*.*   /s /q
del  .\PZIOT.Tasks\obj\*.*   /s /q
del  .\PZIOT.Tests\obj\*.*   /s /q
del  .\Ocelot.Provider.Nacos\obj\*.*   /s /q